version: '2'
services:
  mongodb:
    image: mongo:6.0.8
    ports:
      - "27017:27017"
  party-mode-backend:
    build:
      context: backend
    environment:
      NODE_ENV: development
      PORT: 8081
      LOG_LEVEL: debug
      CORS_ORIGIN: http://127.0.0.1:8080
      SESSION_SECRET: secret
      SESSION_MAX_AGE: 172800000
      SESSION_COLLECTIONNAME: session
      MONGODB_CONNECTIONSTRING: mongodb://localhost:27017
      MONGODB_DATABASENAME: party-mode
    ports:
      - "8081:8081"
    depends_on:
      - mongodb