name: party-mode-prod-deploy
'on':
  push:
    branches:
      - develop
  workflow_dispatch: { }
concurrency:
  group: 'party-mode-prod-deploy-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  prod-deploy:
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Firewall
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: '${{ secrets.DEPLOY_SERVER_HOST }}'
          username: '${{ secrets.DEPLOY_SERVER_SSH_USERNAME }}'
          password: '${{ secrets.DEPLOY_SERVER_SSH_PASSWORD }}'
          command: |
            echo 'y' | ufw enable
            ufw allow 'OpenSSH'
            ufw allow 'Nginx HTTPS'
            ufw default deny incoming
            ufw default allow outgoing
            ufw status verbose
      - name: Install Nginx App Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: '${{ secrets.DEPLOY_SERVER_HOST }}'
          username: '${{ secrets.DEPLOY_SERVER_SSH_USERNAME }}'
          password: '${{ secrets.DEPLOY_SERVER_SSH_PASSWORD }}'
          command: |
            apt install -y nginx
            rm /etc/nginx/nginx.conf
            rm /etc/nginx/sites-available/default
            rm /etc/nginx/sites-enabled/default
            
            # setup ssl certificate and key
            mkdir /etc/nginx/ssl
                  
            cat > /etc/nginx/ssl/party-mode.pem << EOF
            ${{ secrets.DEPLOY_SERVER_SSL_CERT }}
            EOF
            
            openssl rsa -in /etc/nginx/ssl/party-mode.pem -out /etc/nginx/ssl/nginx.key
      - name: Set Nginx Application Configuration
        uses: TwanLuttik/gh-action-scp@1.0.1
        with:
          local: deployment/nginx/nginx.conf
          remote: /etc/nginx/nginx.conf
          host: '${{ secrets.DEPLOY_SERVER_HOST }}'
          username: '${{ secrets.DEPLOY_SERVER_SSH_USERNAME }}'
          password: '${{ secrets.DEPLOY_SERVER_SSH_PASSWORD }}'
      - name: Set Nginx Server Configuration
        uses: TwanLuttik/gh-action-scp@1.0.1
        with:
          local: deployment/nginx/party-mode
          remote: /etc/nginx/sites-available/party-mode
          host: '${{ secrets.DEPLOY_SERVER_HOST }}'
          username: '${{ secrets.DEPLOY_SERVER_SSH_USERNAME }}'
          password: '${{ secrets.DEPLOY_SERVER_SSH_PASSWORD }}'
      - name: Set Nginx Server Configuration (Backend)
        uses: TwanLuttik/gh-action-scp@1.0.1
        with:
          local: deployment/nginx/party-mode-backend
          remote: /etc/nginx/sites-available/party-mode-backend
          host: '${{ secrets.DEPLOY_SERVER_HOST }}'
          username: '${{ secrets.DEPLOY_SERVER_SSH_USERNAME }}'
          password: '${{ secrets.DEPLOY_SERVER_SSH_PASSWORD }}'
      - name: Start Nginx App Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: '${{ secrets.DEPLOY_SERVER_HOST }}'
          username: '${{ secrets.DEPLOY_SERVER_SSH_USERNAME }}'
          password: '${{ secrets.DEPLOY_SERVER_SSH_PASSWORD }}'
          command: |
            ln -s /etc/nginx/sites-available/party-mode /etc/nginx/sites-enabled/party-mode
            ln -s /etc/nginx/sites-available/party-mode-backend /etc/nginx/sites-enabled/party-mode-backend
            service nginx restart
      - name: Deploy Party Mode Website Application
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: '${{ secrets.DEPLOY_SERVER_HOST }}'
          username: '${{ secrets.DEPLOY_SERVER_SSH_USERNAME }}'
          password: '${{ secrets.DEPLOY_SERVER_SSH_PASSWORD }}'
          command: |
            # verify app directory
            mkdir /app
            
            # re-clone repo
            cd /app
            rm -rf party-mode
            git clone --branch bins https://github.com/partymodellc/party-mode.git
            
            # re-setup node cli
            cd /app/party-mode/bin/nodejs
            
            xz -d -v node-v18.17.1-linux-x64.tar.xz
            tar -xf node-v18.17.1-linux-x64.tar
            
            rm /usr/bin/node
            mv node-v18.17.1-linux-x64/bin/node /usr/bin/
            
            # re-create systemd service
            cat > /etc/systemd/system/party-mode-backend.service << EOF
            [Unit]
            Description=Party Mode Backend
            After=network.target
            StartLimitIntervalSec=10
            
            [Service]
            Type=simple
            Restart=always
            RestartSec=1
            StartLimitBurst=5
            StartLimitIntervalSec=15
            User=pmadmin
            ExecStart=node /app/party-mode/backend/index.js
            
            [Install]
            WantedBy=multi-user.target
            EOF
            
            cat > /etc/systemd/system/party-mode-frontend.service << EOF
            [Unit]
            Description=Party Mode Frontend
            After=network.target
            StartLimitIntervalSec=10
            
            [Service]
            Type=simple
            Restart=always
            RestartSec=1
            StartLimitBurst=5
            StartLimitIntervalSec=15
            User=pmadmin
            ExecStart=node /app/party-mode/frontend/index.js
            
            [Install]
            WantedBy=multi-user.target
            EOF
            
            # npm install
            cd /app/party-mode/backend
            NODE_ENV=production /app/party-mode/bin/nodejs/node-v18.17.1-linux-x64/lib/node_modules/npm/bin/npm-cli.js install
            
            cd /app/party-mode/frontend
            NODE_ENV=production /app/party-mode/bin/nodejs/node-v18.17.1-linux-x64/lib/node_modules/npm/bin/npm-cli.js install
            
            # restart service
            service party-mode-backend restart
            service party-mode-frontend restart
