name: party-mode-prod-deploy
'on':
  push:
    branches:
      - develop
  workflow_dispatch: {}
concurrency:
  group: 'party-mode-prod-deploy-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  prod-deploy:
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy Party Mode Website
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: '${{ secrets.DEPLOY_SERVER_HOST }}'
          username: '${{ secrets.DEPLOY_SERVER_SSH_USERNAME }}'
          password: '${{ secrets.DEPLOY_SERVER_SSH_PASSWORD }}'
          command: |
            touch we-made-it-baby.txt
